config/routes.rb
Istockhub::Application.routes.draw do
  get "derivatives/index"
  get "stocks/index"
  get "watchlist/index"
  resources :relationships
  get "usertags/:usertag",   to: "usertags#show",      as: :usertag
  get "usertags",            to: "usertags#index",     as: :usertags
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  get "stock/:moneytag",  to: "moneytags#show",     as: :moneytag
  get "stocks",           to: "moneytags#index",    as: :moneytags
  resources :postings
  get '/:id/following', :to => 'profiles#following', as: :following   
  get '/:id/followers', :to => 'profiles#followers', as: :followers
  
  devise_for :users

  scope :api do
    resources :stocks, defaults: {format: :json} do
      get :ohlc
    end
    get :derivatives, to: 'derivatives#index'
  end
  
  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit
  end

  authenticated :user do
    devise_scope :user do
      root to: "profiles#show", :as => "authenticated"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => "unauthenticated"
    end
  end

  get ':id' => 'profiles#show', as: :profile

end

app/models/posting.rb
class Posting < ActiveRecord::Base
	include Supertag::Hashtaggable 
	include Supertag::Usertaggable 
	include Supertag::Moneytaggable 
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :body, presence: true, length: { maximum: 1000 }
	validates :user_id, presence: true

	def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = current_user.postings.build(posting_params)

    respond_to do |format|
      if @posting.save
        format.html { redirect_to authenticated_path, notice: 'Posting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @posting }
      else
        format.html { redirect_to authenticated_path }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to authenticated_path, notice: 'Posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to authenticated_path }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to authenticated_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:body)
    end
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/postings/_form.html.erb
<%= form_for(@posting) do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% @posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postings/_posting.html.erb
<li>
  <span class="content"><%= posting.body %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(posting.created_at) %> ago.
  </span>
</li>

app/views/postings/edit.html.erb
<h1>Editing posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<h1>Listing postings</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= posting.body %></td>
        <td><%= posting.user_id %></td>
        <td><%= link_to 'Show', posting %></td>
        <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
        <td><%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posting', new_posting_path %>

app/views/postings/new.html.erb
<h1>New posting</h1>

<%= render 'form' %>

<%= link_to 'Back', postings_path %>

app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @posting.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @posting.user_id %>
</p>

<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', postings_path %>