config/routes.rb
Istockhub::Application.routes.draw do
  get "derivatives/index"
  get "stocks/index"
  get "watchlist/index"
  resources :relationships
  get "usertags/:usertag",   to: "usertags#show",      as: :usertag
  get "usertags",            to: "usertags#index",     as: :usertags
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  get "stock/:moneytag",  to: "moneytags#show",     as: :moneytag
  get "stocks",           to: "moneytags#index",    as: :moneytags
  resources :postings
  get '/:id/following', :to => 'profiles#following', as: :following   
  get '/:id/followers', :to => 'profiles#followers', as: :followers
  
  devise_for :users

  scope :api do
    resources :stocks, defaults: {format: :json} do
      get :ohlc
    end
    get :derivatives, to: 'derivatives#index'
  end
  
  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit
  end

  authenticated :user do
    devise_scope :user do
      root to: "profiles#show", :as => "authenticated"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => "unauthenticated"
    end
  end

  get ':id' => 'profiles#show', as: :profile

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def index
    @hashtags = Supertag::Hashtag.all
  end

  def show
    @hashtag = Supertag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/hashtags/index.html.erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %></li>
<% end -%>
</ul>

app/views/hashtags/show.html.erb
<h1><%= params[:hashtag] %></h1>
<% if @hashtagged %>
  <% @hashtagged.each do |hashtagged| %>
    <%= render_hashtaggable hashtagged %>
  <% end -%>
<% else -%>
  <p>There is no match for the <em><%= params[:hashtag] %></em> hashtag.</p>
<% end -%>