config/routes.rb
Istockhub::Application.routes.draw do
  get "derivatives/index"
  get "stocks/index"
  get "watchlist/index"
  resources :relationships
  get "usertags/:usertag",   to: "usertags#show",      as: :usertag
  get "usertags",            to: "usertags#index",     as: :usertags
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  get "stock/:moneytag",  to: "moneytags#show",     as: :moneytag
  get "stocks",           to: "moneytags#index",    as: :moneytags
  resources :postings
  get '/:id/following', :to => 'profiles#following', as: :following   
  get '/:id/followers', :to => 'profiles#followers', as: :followers
  
  devise_for :users

  scope :api do
    resources :stocks, defaults: {format: :json} do
      get :ohlc
    end
    get :derivatives, to: 'derivatives#index'
  end
  
  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit
  end

  authenticated :user do
    devise_scope :user do
      root to: "profiles#show", :as => "authenticated"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => "unauthenticated"
    end
  end

  get ':id' => 'profiles#show', as: :profile

end

app/controllers/moneytags_controller.rb
require 'net/http'
require 'csv'
class MoneytagsController < ApplicationController
  respond_to :json


  def index
    @moneytags = Supertag::Moneytag.all
  end

  def show
    @moneytag = Supertag::Moneytag.find_by_name(params[:moneytag])
    @moneytagged = @moneytag.moneytaggables if @moneytag
    @user = params[:id] ? User.friendly.find(params[:id]) : current_user
  	@username = "@" + @user.username
  	@posting = Posting.new
  	@allpostings = Posting.all

    data = YahooFinance.quotes(["#{@moneytag}"], [:ask, :bid, :low_52_weeks, :high_52_weeks, :name])

    @stock ||= @moneytag ? Stock.create(symbol: @moneytag.name.upcase, 
                                        ask: data[0].ask, 
                                        bid: data[0].bid,
                                        year_low: data[0].low_52_weeks,
                                        year_high: data[0].high_52_weeks,
                                        name: data[0].name) : Stock.find_by_symbol(params[:moneytag])
    @stocksymbol = "$" + @stock.symbol 
  end 

  def following
    @title = "Following"
    @stock = Stock.find(params[:id])
    @stocksymbol = "@" + @stock.symbol
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Following"
    @stock = Stock.find(params[:id])
    @stocksymbol = "@" + @stock.symbol
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
    def stock_params
      params.require(:stock).permit(:id, :symbol, :name, :bid, :ask, :year_low, :year_high)
    end   

end

app/views/moneytags/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @stock.id)) do |f|
  %div= f.hidden_field :followed_id
  = f.submit "Follow", class: "button"

app/views/moneytags/_follow_form.html.haml
#follow_form
  - if current_user.following?(@user)
    = render 'unfollow'
  - else
    = render 'follow'

app/views/moneytags/_show_posts.html.haml
- @allpostings.each do |posting|
  -if posting.body =~ /\$#{@stock.symbol}/
    .row
      .posts
      .container          
        .small-3.columns
          %img.avatar{:src => posting.user.avatar(:thumb), class: 'th'} 
        .small-9.columns  
          .h3
            %strong
              = linkify_tags("@" + posting.user.username)
            = linkify_tags(posting.body)
          %p
          %span.time= time_ago_in_words(posting.created_at) + " ago"
          -if current_user
            = link_to 'Edit', edit_posting_path(posting)
            = link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' }    

app/views/moneytags/_stats.html.haml
%a{:href => followers_path(@stock)}
  %strong
    Followers
    %br
    = @stock.followers.count
    

app/views/moneytags/_unfollow.html.haml
= form_for(current_user.relationships.find_by(followed_id: @stock.id), |
  html: { method: :delete }) do |f|                                   |
  = f.submit "Unfollow", class: "button"

app/views/moneytags/index.html.erb
<h1>Moneytags</h1>
<ul>
<% @moneytags.each do |moneytag| %>
  <li><%= link_to moneytag.name, moneytag_path(moneytag.name) %></li>
<% end -%>
</ul>

app/views/moneytags/index.html.haml
<h1>Moneytags</h1>
<ul>
<% @moneytags.each do |moneytag| %>
  <li><%= link_to moneytag.name, moneytag_path(moneytag.name) %></li>
<% end -%>
</ul>

app/views/moneytags/show.html.haml
%div{"ng-controller" => "StocksCtrl"}
  .row.margin-top
  .large-5.columns.panel.center
    %h1
      = linkify_tags(@stocksymbol)
    /= render 'follow_form' if signed_in?
    %p
      /= render "stats"
    %ul.stock-items  
      #name
        {{stock.name}}
      = succeed {{stock.bid}} do
        %strong Bid:
      = succeed {{stock.ask}} do
        %strong Ask:
      %br  
      = succeed {{stock.year_low}} do
        %strong Year Low:
      = succeed {{stock.year_high}} do
        %strong Year High:
      #links
        Show Chart:
        %input{"ng-model" => "showStockChart", :type => "checkbox"}
      #chart{"my-chart" => "", "ng-show" => "showStockChart", :stockid => "stock.id", :stockname => "stock.name", :stocksymbol => "stock.symbol", :style => "padding-right: 30px; padding-left: 20px;padding-top: 15px;"}
        #loading_chart
          Loading Chart, this might take a while!                                     
  .large-7.columns
    .row.panel
      .small-4.columns
        %h4 Create Post
      .small-6.columns  
        = form_for @posting do |f|
          .row.collapse
            .small-10.columns
              = f.text_area :body, class: 'text'
            .small-2.columns  
              = f.submit "Post", class: 'button'
      .small-2.columns        
    .panel             
      .center           
        %h2 Posts
      %br
        = render "show_posts" 