config/routes.rb
Istockhub::Application.routes.draw do
  get "derivatives/index"
  get "stocks/index"
  get "watchlist/index"
  resources :relationships
  get "usertags/:usertag",   to: "usertags#show",      as: :usertag
  get "usertags",            to: "usertags#index",     as: :usertags
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  get "stock/:moneytag",  to: "moneytags#show",     as: :moneytag
  get "stocks",           to: "moneytags#index",    as: :moneytags
  resources :postings
  get '/:id/following', :to => 'profiles#following', as: :following   
  get '/:id/followers', :to => 'profiles#followers', as: :followers
  
  devise_for :users

  scope :api do
    resources :stocks, defaults: {format: :json} do
      get :ohlc
    end
    get :derivatives, to: 'derivatives#index'
  end
  
  get "profiles/show"

  devise_scope :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit
  end

  authenticated :user do
    devise_scope :user do
      root to: "profiles#show", :as => "authenticated"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => "unauthenticated"
    end
  end

  get ':id' => 'profiles#show', as: :profile

end

app/views/layouts/application.html.haml
!!!
%html{"ng-app" => "istockhub"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "i$tockHub"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    %nav.top-bar{"data-topbar" => ""}
      %ul.title-area
        %li.name
          %h1
            %a{:href => "/"} i$tockHub
        %li.toggle-topbar.menu-icon
          %a{:href => "#"} Menu
      %section.top-bar-section
        / Right Nav Section
        %ul.right
          - if user_signed_in?
            %li= link_to "Edit Profile", edit_user_registration_path
            %li= link_to "Log Out", logout_path
            %li= link_to "My Profile", profile_path(current_user)
          - else
            %li= link_to "Sign Up", register_path
            %li= link_to "Log In", login_path
        / Left Nav Section
        %ul.left
    = yield
    = javascript_include_tag "application"